unshare: Propagate /boot automount to mount ns
Pass --propagation=slave so that if systemd gpt-auto-generator has
automount for /boot it gets propagated inside the new mount ns
for us to be able to access the /boot mount even if it's expired

Without this all bootc commands fail with

```
error: Initializing storage: opendir(boot): Operation not permitted
```

Closes: #2402

Signed-off-by: Pragyan Poudyal <pragyanpoudyal41999@gmail.com>