test: Fix bib test failure and add required package in bib test
error: cannot build manifest: no default fs set: mount "/boot"
requires a filesystem but none set

Signed-off-by: Xiaofeng Wang <henrywangxf@me.com>